server:
    context-path: /atech
    port: 8080

info:
    project:
        name: atech
        version: @project.version@

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
logging.level:
  root: DEBUG
  org.springframework.boot.autoconfigure.logging: ERROR
  
liquibase:
  change-log: classpath:config/liquibase/master.xml
  enabled: true
  drop-first: false

spring:
    profiles.active: @build.profile.id@
    application:
        name: proimport-app
    datasource:
        url: jdbc:postgresql://localhost:5432/proimport
        name: proimport
        username: proimport
        password: proimport
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        open-in-view: false
        show-sql: true
        hibernate:
            ddl-auto: none
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.hbm2ddl.auto: none